name: 'Create Branch from Issue'

# GitHub App/Action Create Issue Branch: https://github.com/robvanderleek/create-issue-branch

on:
  # The issues event below is only needed for the default (auto) mode, you can remove it otherwise.
  issues:
    types: [ assigned ]

jobs:
  create_issue_branch:
    runs-on: ubuntu-latest

    steps:
      - name: 'Create Branch from Issue'
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}